# Generated by Django 3.2.5 on 2021-08-05 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher', to='auctions.listing')),
                ('xList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
