# Generated by Django 3.2.5 on 2021-08-05 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='watching',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='xList',
        ),
        migrations.AddField(
            model_name='watch',
            name='eyesOn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watch',
            name='watchList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='auctions.listing'),
        ),
    ]
