# Generated by Django 3.2.5 on 2021-08-07 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210805_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchedBy',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='watch',
        ),
    ]
