# Generated by Django 3.2.5 on 2021-08-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210807_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currentBid',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentBider', to='auctions.listing'),
        ),
    ]
